services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      # Secrets pour la signature des tokens
      JWT_KEY: 'qerggrgqrgqregsgfhjyudqgyjdtht'
      PUBLISHER_JWT_KEY: 'qerggrgqrgqregsgfhjyudqgyjdtht'
      SUBSCRIBER_JWT_KEY: 'qerggrgqrgqregsgfhjyudqgyjdtht'

      #CORS pour React (localhost:5173)
      CORS_ALLOWED_ORIGINS: 'http://localhost:5173'

      #Optionnel : permet de s’abonner sans token (pratique en dev)
      ALLOW_ANONYMOUS: '1'

      #Permet les updates depuis des requêtes HTTP POST (utile avec Symfony)
      ALLOW_PUBLISH: '1'

      #Permet les logs en dev
      DEBUG: '1'
