nelmio_api_doc:
  documentation:
    info:
      title: Supchat
      version: 1.0.0
      description: une API de chat pour une entreprise
    file: '%kernel.project_dir%/public/docs/openapi.yaml'

  areas:
    default:             # ⚠️ Obligatoire, même si inutilisé
      path_patterns: []  # => aucune route ne sera scannée
      disable_default_routes: true
