nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_credentials: false
        allow_headers: ['*']
        allow_methods: ['OPTIONS', 'GET']
        expose_headers: ['*']
        max_age: 3600

    paths:
        '^/api/':
            origin_regex: false
            allow_origin: ['http://localhost:5173']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
            expose_headers: ['Content-Type', 'Authorization']
            max_age: 3600

        '^/subscribe':
            origin_regex: false
            allow_origin: ['*'] # pour /subscribe on s'en fiche en dev
            allow_credentials: false
            allow_headers: ['*']
            allow_methods: ['OPTIONS', 'GET']
            expose_headers: ['*']
            max_age: 3600
