security:
    password_hashers:
        App\Entity\Users:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: emailAddress

    firewalls:
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JwtAuthenticator
                - App\Security\GoogleAuthenticator
                - App\Security\FacebookAuthenticator


        connect:
            pattern: ^/connect/
            stateless: true
            provider: app_user_provider
            custom_authenticators:
              - App\Security\GoogleAuthenticator
              - App\Security\FacebookAuthenticator
              
    access_control:
        - { path: ^/api/files/download$, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc(?:\.json)?$, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/google, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/facebook, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }  
